working_directory: /usr/src/app
# the netrc_filename value must be a fully-qualified name
# netrc_filename: /usr/src/app/netrc
proxy_file_name: /usr/src/app/cadcproxy.pem
# operational value is ivo://cadc.nrc.ca/caom2repo
resource_id: ivo://cadc.nrc.ca/sc2repo
# operational value is ivo://cadc.nrc.ca/ams/neossat
tap_id: ivo://cadc.nrc.ca/sc2tap
todo_file_name: todo.txt
# values True False
use_local_files: False
# values DEBUG INFO WARNING ERROR
logging_level: DEBUG
# values True False
log_to_file: True
# fully qualified name for a directory to write log files
log_file_directory: /usr/src/app/logs
# the filename where success logs are written
#
# this file is created in the logs directory, default is 'success_log.txt'
success_log_file_name: success_log.txt
# the filename where failure logs are written
#
# this file is created in the logs directory, default is 'failure_log.txt'
failure_log_file_name: failure_log.txt
# the filename where retry ids are written. This file is only written
# if use_local_files is False.
#
# this file is created in the logs directory, default is 'retries.txt'
retry_file_name: retries.txt
# the filename where pipeline progress is written. This file is
# always written. Logs progress between invocations, and is useful 
# when using time-boxed execution.
#
# this file is created in the logs directory, default is 'progress.txt'
progress_file_name: progress.txt
#
# ad stream value - sorry
stream: default
archive: NEOSS
collection: NEOSSAT
#
# CADC service execution metrics
#
observe_execution: True
observable_directory: /usr/src/app/metrics
# 
# track known failures in this location
# 
rejected_file_name: rejected.yml
rejected_directory: /usr/src/app/rejected
#
state_file_name: state.yml
interval: 600
source_host: ftp.asc-csa.gc.ca
# how to control the work that gets done
# possible values are:
# - scrape - read the headers, write out the xml - kind of a test mode
# - store - calls cadc-data to put a file from local storage (use_local_files must be set to True)
# - ingest - read the headers, write the xml to the endpoint found by resource_id
# - modify - create a footprint and previews for an existing CAOM model record
# - pull - put a file retrieved from a URL
task_types: 
  - ingest
  - modify
features:
  supports_composite: False
  use_file_names: True
  use_urls: False
